### ISSUE TITLE
RelationField does not take into account the ordering

### ISSUE THREAD

**Issue by Mogost** [trashnroll/django-abnorm#7]
```
class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)

class Post(models.Model):
    first_five_comments = abnorm.RelationField(
        relation_name='comment_set',
        qs_filter={'is_deleted': False},
        limit=5)
```
As far as I can see, in this example from README is an error. To denormalize abnorm will make query to db like this
`Comment.objects.filter(is_deleted=False)[:5]`
that will be translated to 
`SELECT id, post, is_deleted FROM comment WHERE is_deleted  == False  LIMIT 5`
this query not take into account ordering.
Of course, in most cases, the DB will return them in order of PK, but this is not definitely. [stackoverflow](https://stackoverflow.com/a/9357159/5628843)
Correct behavior should explicitly work with ordering. It also allows you to get not only the first 5, but also the last 5 lines.
I apologize in advance if I missed some part of the code where it counts.

**Comment by trashnroll** [comment]
This behavior is expected and correct, as Comment model has no explicit ordering definition (see https://docs.djangoproject.com/en/2.1/ref/models/options/#django.db.models.Options.ordering), so django ORM omits `order by` clause for generated SQL statement.

Here is a logged query for the modified Comment model with appropriate ordering option set:

`SELECT "blog_comment"."id", "blog_comment"."post_id", "blog_comment"."is_deleted" FROM "blog_comment" WHERE "blog_comment"."is_deleted" = 0 ORDER BY "blog_comment"."id" ASC  LIMIT 5; args=(False,)`

However, there really should be an option to override such default qs ordering for each RelationField instance, yet that seems to be a subject for a separate issue.

Thanks for your feedback.

**Comment by Mogost** [comment]
I know about django models ordering option. But in example from documentation ordering option is not set. Variable `first_five_comments` is misleading since it is impossible to speak about first or last items if they are not sorted. 
At a minimum it is worth paying attention to this point in the documentation. It may be worthwhile to throw an exception if the model does not have explicit sorting.
This issue can be considered a request for improved documentation.
